web:
  build: .
  ports:
    - "3000:3000"
  links:
    - "mongo"
  environment:
    - "USERNAME=${USERNAME}"
    - "PASSWORD=${PASSWORD}"

mongo:
  image: "mongo"
  volumes:
    - "db:/data/db"
  ports:
    - "27017:27017"