web:
  image: lafin/ru-yts:armhf
  ports:
    - "3000:3000"
  links:
    - "mongo"
  volumes:
    - "./log:/ru-yts-master/log"

mongo:
  image: "partlab/ubuntu-arm-mongodb"
  volumes:
    - "./db:/data/db"